# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_quick_guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_quickguide(object):
    def setupUi(self, dialog_quickguide):
        dialog_quickguide.setObjectName("dialog_quickguide")
        dialog_quickguide.setEnabled(True)
        dialog_quickguide.resize(978, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_quickguide.sizePolicy().hasHeightForWidth())
        dialog_quickguide.setSizePolicy(sizePolicy)
        dialog_quickguide.setMinimumSize(QtCore.QSize(0, 0))
        dialog_quickguide.setMaximumSize(QtCore.QSize(1149, 693))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../GigaMesh/GigaMesh/.designer/backup/GigaMesh_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog_quickguide.setWindowIcon(icon)
        dialog_quickguide.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_quickguide)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(dialog_quickguide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setAcceptDrops(False)
        self.textBrowser.setStyleSheet("background-color:transparent")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialog_quickguide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(100, 80))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dialog_quickguide)
        self.buttonBox.accepted.connect(dialog_quickguide.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_quickguide.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_quickguide)

    def retranslateUi(self, dialog_quickguide):
        _translate = QtCore.QCoreApplication.translate
        dialog_quickguide.setWindowTitle(_translate("dialog_quickguide", "Dialog"))
        self.textBrowser.setHtml(_translate("dialog_quickguide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<h2 align=\"center\" style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"quick-guide\"></a><span style=\" font-size:x-large; font-weight:600;\">Q</span><span style=\" font-size:x-large; font-weight:600;\">uick Guide</span></h2>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"-1-load-ply-file-\"></a><span style=\" font-size:large; font-weight:600;\">1</span><span style=\" font-size:large; font-weight:600;\">. Load ply file</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">Load ply</span> under the <span style=\" font-style:italic;\">File</span> menu. Note that you need a .ply file that contains a function value under <span style=\" font-weight:600;\">quality</span>. </p>\n"
"<h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"-comments-on-the-mesh-\"></a><span style=\" font-size:medium; font-weight:600;\">C</span><span style=\" font-size:medium; font-weight:600;\">omments on the mesh:</span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please make sure that your mesh has a manifold-like structure, i.e. especially there should be no edges with more than 2 adjacent triangles. Holes or boundaries in the mesh are no problem algorithmically, but depending on the application it might make sense to fill them. To do mesh preprocessing we recommend using e.g. <a href=\"https://gigamesh.eu/\"><span style=\" text-decoration: underline; color:#0000ff;\">GigaMesh</span></a>.</p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"-2-compute-morse-complex-\"></a><span style=\" font-size:large; font-weight:600;\">2</span><span style=\" font-size:large; font-weight:600;\">. Compute Morse Complex</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Compute the Morse complex for a loaded mesh in the <span style=\" font-style:italic;\">Compute</span> menu under <span style=\" font-style:italic;\">Compute Morse complex</span>.</p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"-3-determine-edges-\"></a><span style=\" font-size:large; font-weight:600;\">3</span><span style=\" font-size:large; font-weight:600;\">. Determine edges</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can now use the two sliders in the bottom to determine the edges correctly. Just move them and the mesh will update automatically. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The upper slider determines a <span style=\" font-weight:600;\">strong threshold</span> which includes all edges surpassing this threshold, while the lower slider determines the <span style=\" font-weight:600;\">weak threshold</span> which adds only edges that are below the strong threshold, but above the weak threshold, therefore refining the result a bit.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Under <span style=\" font-style:italic;\">advanced edge detection</span> in the sidebar you can choose more edge settings, the only ones that might be interesting though are the &quot;Separatrix density<span style=\" font-style:italic;\"> which could be ticked to </span>All<span style=\" font-style:italic;\"> or the </span>Extremal line type<span style=\" font-style:italic;\">, which can be switched between </span>ridges<span style=\" font-style:italic;\"> and </span>valleys*. </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"-4-segmentation-\"></a><span style=\" font-size:large; font-weight:600;\">4</span><span style=\" font-size:large; font-weight:600;\">. Segmentation</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use the <span style=\" font-weight:600;\">Morse segmentation method</span> or the <span style=\" font-weight:600;\">Cluster segmentation method</span> in the <span style=\" font-style:italic;\">Segmentations</span> menu. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can change parameters of the segmentation in the sidebar under <span style=\" font-style:italic;\">Morse segmentation</span> or <span style=\" font-style:italic;\">Cluster segmentation</span>.</p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"-5-save-result-\"></a><span style=\" font-size:large; font-weight:600;\">5</span><span style=\" font-size:large; font-weight:600;\">. Save result</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can rerun the segmentations until you have a sufficient result. The segmentation can be saved as a label.txt file in the <span style=\" font-style:italic;\">File</span> menu. </p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_quickguide = QtWidgets.QDialog()
    ui = Ui_dialog_quickguide()
    ui.setupUi(dialog_quickguide)
    dialog_quickguide.show()
    sys.exit(app.exec_())
